GallerySharp/src/GallerySharp/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using GallerySharp.Data.GalleryRepository;
using Microsoft.AspNetCore.Authorization;

namespace GallerySharp.Controllers
{
    [Authorize]
    public class AdministrationController : Controller
    {
        private readonly IGalleryRepository _repository;

        public AdministrationController(IGalleryRepository repository)
        {
            _repository = repository;
        }
        public ActionResult Index()
        {
            return View(_repository.getAllPhotos());
        }

        public ActionResult PointDownPhoto(string id)
        {
            if (ModelState.IsValid)
            {
                _repository.pointDownPhoto(new Guid(id));
            }
            return RedirectToAction("Index");
        }

        public ActionResult PointOutPhoto(string id)
        {
            if (ModelState.IsValid)
            {
                _repository.pointOutPhoto(new Guid(id));
            }
            return RedirectToAction("Index");
        }
    }
}

GallerySharp/src/GallerySharp/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using GallerySharp.Data.GalleryRepository;
using GallerySharp.Models;
using Microsoft.AspNetCore.Identity;
using GallerySharp.Models.GalleryViewModels;
using GallerySharp.Models.GalleryModels;
using Microsoft.AspNetCore.Authorization;

namespace GallerySharp.Controllers
{
    [Authorize]
    public class AlbumController : Controller
    {
        private readonly IGalleryRepository _repository;
        private readonly UserManager<ApplicationUser> _userManager;

        public AlbumController(IGalleryRepository repository, UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            bool doesHaveProfile = _repository.doesUserHaveProfile(currentUser.Id);
            if (!doesHaveProfile)
            {
                return RedirectToAction("CreateProfile");
            }
            ViewBag.usId = new Guid(currentUser.Id);
            ViewBag.userName = _repository.getProfileUserName(currentUser.Id);
            ViewBag.subs = _repository.getUserSubscriptionsIds(currentUser.Id);
            ViewBag.users = _repository.getAllUsersExcept(currentUser.Id);
            return View(_repository.getAllAlbums());
        }

        public ActionResult CreateProfile()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProfile(CreateProfileView m)
        {
            if (ModelState.IsValid)
            {
                if (!_repository.doesUserNameExists(m.UserName))
                {
                    ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

                    _repository.createNewProfile(currentUser.Id, m.UserName);
                    return RedirectToAction("Index", "Home");
                }
            }
            ViewBag.errorMessage = "User name already taken!";
            return View(m);
        }

        public ActionResult CreateAlbum()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAlbum(CreateAlbumView m)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
                _repository.createNewAlbum(currentUser.Id, m.AlbumName, _repository.getProfileUserName(currentUser.Id));
                return RedirectToAction("Index");
            }
            return View(m);
        }

        public async Task<IActionResult> DeleteAlbum(Guid id)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (_repository.albumExists(currentUser.Id, id))
            {
                _repository.deleteAlbum(id);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeletePhoto(Guid id)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
                _repository.deletePhoto(currentUser.Id, id);
            }
            return RedirectToAction("ViewAlbum");
        }

        public async Task<IActionResult> ViewAlbum(Guid id)
        {

            if (id != null && !id.ToString().StartsWith("000"))
            {
                HttpContext.Session.Set("albumId", id.ToByteArray());
            }
            else
            {
                id = new Guid(HttpContext.Session.Get("albumId"));
            }
            Album album = _repository.getAlbum(id);
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            ViewBag.userId = new Guid(currentUser.Id);
            return View(album);
        }

        public ActionResult AddPhoto()
        {

            ViewData["albumId"] = new Guid(HttpContext.Session.Get("albumId"));
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPhoto(Guid id, string PhotoName, IFormFile upload)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (ModelState.IsValid)
            {
                if (PhotoName != null && upload != null && upload.Length > 0)
                {
                    _repository.addPhoto(id, currentUser.Id, PhotoName, upload);
                    return RedirectToAction("ViewAlbum");
                }
            }
            return View();
        }


        public ActionResult ViewPhoto(Guid id)
        {
            if (id != null && !id.ToString().StartsWith("000"))
            {
                Guid albumId = _repository.getAlbumIdOfPhoto(id);
                HttpContext.Session.Set("photoId", id.ToByteArray());
                HttpContext.Session.Set("albumId", albumId.ToByteArray());
            }
            else
            {
                id = new Guid(HttpContext.Session.Get("photoId"));
            }
            Photo photo = _repository.getPhoto(id);
            return View(photo);
        }

        public ActionResult LikePhoto(Guid id)
        {
            _repository.likePhoto(id);
            return RedirectToAction("ViewPhoto", id);
        }

        public ActionResult DislikePhoto(Guid id)
        {
            _repository.dislikePhoto(id);
            return RedirectToAction("ViewPhoto", id);
        }

        public ActionResult CreateComment()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComment(CreateCommentView m)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
                Guid photoId = new Guid(HttpContext.Session.Get("photoId"));
                ViewBag.photoId = photoId;
                _repository.addCommentToPhoto(photoId, currentUser.Id, m.CommentText);
                return RedirectToAction("ViewPhoto", photoId);
            }
            return View(m);
        }

        public ActionResult ChangePhotoName(string id)
        {
            if (ModelState.IsValid)
            {
                Guid photoId = new Guid(id);
                if (photoId != null && !photoId.ToString().StartsWith("000"))
                {
                    Guid albumId = _repository.getAlbumIdOfPhoto(photoId);
                    HttpContext.Session.Set("photoId", photoId.ToByteArray());
                }
                else
                {
                    photoId = new Guid(HttpContext.Session.Get("photoId"));
                }
                ViewBag.oldPhotoName = _repository.getPhotoName(photoId);
                return View();
            }
            return RedirectToAction("ViewAlbum");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePhotoName(ChangePhotoNameView m)
        {
            if (ModelState.IsValid)
            {
                Guid photoId = new Guid(HttpContext.Session.Get("photoId"));
                _repository.changePhotoName(photoId, m.NewPhotoName);
                return RedirectToAction("ViewAlbum");
            }
            return View(m);

        }

        public ActionResult ChangeAlbumName(string id)
        {
            if (ModelState.IsValid)
            {
                Guid albumId = new Guid(id);
                if (albumId != null && !albumId.ToString().StartsWith("000"))
                {
                    HttpContext.Session.Set("albumId", albumId.ToByteArray());
                }
                else
                {
                    albumId = new Guid(HttpContext.Session.Get("albumId"));
                }
                ViewBag.oldAlbumName = _repository.getAlbumName(albumId);
                return View();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeAlbumName(ChangeAlbumNameView m)
        {
            if (ModelState.IsValid)
            {
                Guid albumId = new Guid(HttpContext.Session.Get("albumId"));
                _repository.changeAlbumName(albumId, m.NewAlbumName);
                return RedirectToAction("Index");
            }
            return View(m);
        }

        public async Task<IActionResult> AddPhotoToFavorites(string id)
        {
            Guid photoG = new Guid(id);
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            _repository.addPhotoToFavorites(new Guid(currentUser.Id), photoG);
            return RedirectToAction("ViewPhoto");
        }


        public async Task<IActionResult> SubscribeToUser(string id)
        {
            Guid userGSub = new Guid(id);
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            _repository.subscribeToUser(new Guid(currentUser.Id), userGSub);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UnsubscribeToUser(string id)
        {
            Guid userGSub = new Guid(id);
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            _repository.unsubscribeToUser(new Guid(currentUser.Id), userGSub);
            return RedirectToAction("Index");
        }
    }
}

GallerySharp/src/GallerySharp/Controllers/FavoritesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GallerySharp.Data.GalleryRepository;
using Microsoft.AspNetCore.Identity;
using GallerySharp.Models;
using Microsoft.AspNetCore.Authorization;

namespace GallerySharp.Controllers
{
    [Authorize]
    public class FavoritesController : Controller
    {

        private readonly IGalleryRepository _repository;
        private readonly UserManager<ApplicationUser> _userManager;

        public FavoritesController(IGalleryRepository repository, UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            bool doesHaveProfile = _repository.doesUserHaveProfile(currentUser.Id);
            if (!doesHaveProfile)
            {
                return RedirectToAction("CreateProfile", "Album");
            }
            Guid userG = new Guid(currentUser.Id);
            return View(_repository.getAllUserFavorites(userG));
        }

        public async Task<IActionResult> RemovePhotoFromFavorites(string id)
        {
            Guid photoG = new Guid(id);
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            _repository.removePhotoFromFavorites(new Guid(currentUser.Id), photoG);
            return RedirectToAction("Index");
        }
    }
}

GallerySharp/src/GallerySharp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GallerySharp</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">GallerySharp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                        byte[] userType;
                        Context.Session.TryGetValue("userType", out userType);
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (userType[0] == 2)
                    {
                        <li><a asp-area="" asp-controller="Album" asp-action="Index">Albums</a></li>
                        <li><a asp-area="" asp-controller="Favorites" asp-action="Index">Favorites</a></li>
                    }
                    @if (userType[0] == 1)
                    {
                        <li><a asp-area="" asp-controller="Administration" asp-action="Index">Administration</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - GallerySharp</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>