GallerySharp/src/GallerySharp/Models/GalleryModels/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GallerySharp.Models.GalleryModels
{
    public class Album
    {
        public Guid AlbumID { get; set; }
        public string AlbumName { get; set; }
        public Guid UserID { get; set; }
        public string UserName { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual ICollection<Photo> Photos { get; set; }

        public Album()
        {

        }

        public Album(string userId, string albumName, string userName)
        {
            AlbumID = Guid.NewGuid();
            AlbumName = albumName;
            UserID = new Guid(userId);
            UserName = userName;
            CreationDate = DateTime.Now;
        }

    }
}

GallerySharp/src/GallerySharp/Models/GalleryViewModels/ChangeAlbumNameView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GallerySharp.Models.GalleryViewModels
{
    public class ChangeAlbumNameView
    {
        [Required]
        [MinLength(4, ErrorMessage = "Minimun 4 characters expected.")]
        [StringLength(15, ErrorMessage = "Maximum 15 characters expected.")]
        [Display(Name = "New Photo Name")]
        public string NewAlbumName { get; set; }
    }
}

GallerySharp/src/GallerySharp/Models/GalleryViewModels/ChangePhotoNameView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GallerySharp.Models.GalleryViewModels
{
    public class ChangePhotoNameView
    {
        [Required]
        [MinLength(4, ErrorMessage = "Minimun 4 characters expected.")]
        [StringLength(15, ErrorMessage = "Maximum 15 characters expected.")]
        [Display(Name = "New Photo Name")]
        public string NewPhotoName { get; set; }
    }
}

GallerySharp/src/GallerySharp/Models/GalleryViewModels/CreateAlbumView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GallerySharp.Models.GalleryViewModels
{
    public class CreateAlbumView
    {
        [Required]
        [MinLength(4, ErrorMessage = "Minimun 4 characters expected.")]
        [StringLength(15, ErrorMessage = "Maximum 15 characters expected.")]
        [Display(Name = "Album name")]
        public string AlbumName { get; set; }
    }
}

GallerySharp/src/GallerySharp/Models/GalleryViewModels/CreateCommentView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GallerySharp.Models.GalleryViewModels
{
    public class CreateCommentView
    {
        [Required]
        [MinLength(1, ErrorMessage = "Minimun 1 characters expected.")]
        [StringLength(300, ErrorMessage = "Maximum 300 characters expected.")]
        [Display(Name = "Enter Comment")]
        public string CommentText { get; set; }
    }
}

GallerySharp/src/GallerySharp/Models/GalleryViewModels/CreateProfileView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GallerySharp.Models.GalleryViewModels
{
    public class CreateProfileView
    {
        [Required]
        [MinLength(4, ErrorMessage = "Minimun 4 characters expected.")]
        [StringLength(15, ErrorMessage = "Maximum 15 characters expected.")]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }
}

GallerySharp/src/GallerySharp/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using GallerySharp.Data.GalleryRepository;
using GallerySharp.Models;
using Microsoft.AspNetCore.Identity;
using GallerySharp.Models.GalleryViewModels;
using GallerySharp.Models.GalleryModels;
using Microsoft.AspNetCore.Authorization;

namespace GallerySharp.Controllers
{
    [Authorize]
    public class AlbumController : Controller
    {
        private readonly IGalleryRepository _repository;
        private readonly UserManager<ApplicationUser> _userManager;

        public AlbumController(IGalleryRepository repository, UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            bool doesHaveProfile = _repository.doesUserHaveProfile(currentUser.Id);
            if (!doesHaveProfile)
            {
                return RedirectToAction("CreateProfile");
            }
            ViewBag.usId = new Guid(currentUser.Id);
            ViewBag.userName = _repository.getProfileUserName(currentUser.Id);
            ViewBag.subs = _repository.getUserSubscriptionsIds(currentUser.Id);
            ViewBag.users = _repository.getAllUsersExcept(currentUser.Id);
            return View(_repository.getAllAlbums());
        }

        public ActionResult CreateProfile()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProfile(CreateProfileView m)
        {
            if (ModelState.IsValid)
            {
                if (!_repository.doesUserNameExists(m.UserName))
                {
                    ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

                    _repository.createNewProfile(currentUser.Id, m.UserName);
                    return RedirectToAction("Index", "Home");
                }
            }
            ViewBag.errorMessage = "User name already taken!";
            return View(m);
        }

        public ActionResult CreateAlbum()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAlbum(CreateAlbumView m)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
                _repository.createNewAlbum(currentUser.Id, m.AlbumName, _repository.getProfileUserName(currentUser.Id));
                return RedirectToAction("Index");
            }
            return View(m);
        }

        public async Task<IActionResult> DeleteAlbum(Guid id)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (_repository.albumExists(currentUser.Id, id))
            {
                _repository.deleteAlbum(id);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeletePhoto(Guid id)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
                _repository.deletePhoto(currentUser.Id, id);
            }
            return RedirectToAction("ViewAlbum");
        }

        public async Task<IActionResult> ViewAlbum(Guid id)
        {

            if (id != null && !id.ToString().StartsWith("000"))
            {
                HttpContext.Session.Set("albumId", id.ToByteArray());
            }
            else
            {
                id = new Guid(HttpContext.Session.Get("albumId"));
            }
            Album album = _repository.getAlbum(id);
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            ViewBag.userId = new Guid(currentUser.Id);
            return View(album);
        }

        public ActionResult AddPhoto()
        {

            ViewData["albumId"] = new Guid(HttpContext.Session.Get("albumId"));
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPhoto(Guid id, string PhotoName, IFormFile upload)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (ModelState.IsValid)
            {
                if (PhotoName != null && upload != null && upload.Length > 0)
                {
                    _repository.addPhoto(id, currentUser.Id, PhotoName, upload);
                    return RedirectToAction("ViewAlbum");
                }
            }
            return View();
        }


        public ActionResult ViewPhoto(Guid id)
        {
            if (id != null && !id.ToString().StartsWith("000"))
            {
                Guid albumId = _repository.getAlbumIdOfPhoto(id);
                HttpContext.Session.Set("photoId", id.ToByteArray());
                HttpContext.Session.Set("albumId", albumId.ToByteArray());
            }
            else
            {
                id = new Guid(HttpContext.Session.Get("photoId"));
            }
            Photo photo = _repository.getPhoto(id);
            return View(photo);
        }

        public ActionResult LikePhoto(Guid id)
        {
            _repository.likePhoto(id);
            return RedirectToAction("ViewPhoto", id);
        }

        public ActionResult DislikePhoto(Guid id)
        {
            _repository.dislikePhoto(id);
            return RedirectToAction("ViewPhoto", id);
        }

        public ActionResult CreateComment()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComment(CreateCommentView m)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
                Guid photoId = new Guid(HttpContext.Session.Get("photoId"));
                ViewBag.photoId = photoId;
                _repository.addCommentToPhoto(photoId, currentUser.Id, m.CommentText);
                return RedirectToAction("ViewPhoto", photoId);
            }
            return View(m);
        }

        public ActionResult ChangePhotoName(string id)
        {
            if (ModelState.IsValid)
            {
                Guid photoId = new Guid(id);
                if (photoId != null && !photoId.ToString().StartsWith("000"))
                {
                    Guid albumId = _repository.getAlbumIdOfPhoto(photoId);
                    HttpContext.Session.Set("photoId", photoId.ToByteArray());
                }
                else
                {
                    photoId = new Guid(HttpContext.Session.Get("photoId"));
                }
                ViewBag.oldPhotoName = _repository.getPhotoName(photoId);
                return View();
            }
            return RedirectToAction("ViewAlbum");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePhotoName(ChangePhotoNameView m)
        {
            if (ModelState.IsValid)
            {
                Guid photoId = new Guid(HttpContext.Session.Get("photoId"));
                _repository.changePhotoName(photoId, m.NewPhotoName);
                return RedirectToAction("ViewAlbum");
            }
            return View(m);

        }

        public ActionResult ChangeAlbumName(string id)
        {
            if (ModelState.IsValid)
            {
                Guid albumId = new Guid(id);
                if (albumId != null && !albumId.ToString().StartsWith("000"))
                {
                    HttpContext.Session.Set("albumId", albumId.ToByteArray());
                }
                else
                {
                    albumId = new Guid(HttpContext.Session.Get("albumId"));
                }
                ViewBag.oldAlbumName = _repository.getAlbumName(albumId);
                return View();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeAlbumName(ChangeAlbumNameView m)
        {
            if (ModelState.IsValid)
            {
                Guid albumId = new Guid(HttpContext.Session.Get("albumId"));
                _repository.changeAlbumName(albumId, m.NewAlbumName);
                return RedirectToAction("Index");
            }
            return View(m);
        }

        public async Task<IActionResult> AddPhotoToFavorites(string id)
        {
            Guid photoG = new Guid(id);
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            _repository.addPhotoToFavorites(new Guid(currentUser.Id), photoG);
            return RedirectToAction("ViewPhoto");
        }


        public async Task<IActionResult> SubscribeToUser(string id)
        {
            Guid userGSub = new Guid(id);
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            _repository.subscribeToUser(new Guid(currentUser.Id), userGSub);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UnsubscribeToUser(string id)
        {
            Guid userGSub = new Guid(id);
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            _repository.unsubscribeToUser(new Guid(currentUser.Id), userGSub);
            return RedirectToAction("Index");
        }
    }
}

GallerySharp/src/GallerySharp/Views/Album/AddPhoto.cshtml
@model GallerySharp.Models.GalleryModels.Photo

@{
    ViewData["Title"] = "Add New Photo";
}

<h2>Add New Photo</h2>

<form method="post" asp-action="AddPhoto" asp-controller="Album" enctype="multipart/form-data" id=@ViewData["albumId"]>
    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <div class="form-group">
            <label asp-for="PhotoName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PhotoName" class="form-control" required/>
                <span asp-validation-for="PhotoName" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="file" name="upload" required/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
       
    </div>
</form>


<div>
    @Html.ActionLink("Back to the Album", "ViewAlbum", new { id = ViewData["albumId"] })
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GallerySharp/src/GallerySharp/Views/Album/ChangeAlbumName.cshtml
@model GallerySharp.Models.GalleryViewModels.ChangeAlbumNameView

@{
    ViewData["Title"] = "Change Album Name";
}

<h2>Set New Name For Album</h2>

<form asp-action="ChangeAlbumName">
    <div class="form-horizontal">
        <br />
        <h4>Old Name: @ViewBag.oldAlbumName</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="NewAlbumName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="NewAlbumName" class="form-control" />
                <span asp-validation-for="NewAlbumName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Set" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Cancel</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GallerySharp/src/GallerySharp/Views/Album/ChangePhotoName.cshtml
@model GallerySharp.Models.GalleryViewModels.ChangePhotoNameView

@{
    ViewData["Title"] = "Change Photo Name";
}

<h2>ChangePhotoName</h2>

<form asp-action="ChangePhotoName">
    <div class="form-horizontal">
        <br />
        <h4>Old photo name: @ViewBag.oldPhotoName</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="NewPhotoName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="NewPhotoName" class="form-control" />
                <span asp-validation-for="NewPhotoName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Change" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="ViewAlbum">Cancel</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GallerySharp/src/GallerySharp/Views/Album/CreateAlbum.cshtml
@model GallerySharp.Models.GalleryViewModels.CreateAlbumView

@{
    ViewData["Title"] = "Create Album";
}

<h2>Create New Album</h2>

<form asp-action="CreateAlbum">
    <div class="form-horizontal">
        <br />
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="AlbumName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AlbumName" class="form-control" />
                <span asp-validation-for="AlbumName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to Albums</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GallerySharp/src/GallerySharp/Views/Album/CreateComment.cshtml
@model GallerySharp.Models.GalleryViewModels.CreateCommentView

@{
    ViewData["Title"] = "Create Comment";
}

<h2>CreateComment</h2>

<form asp-action="CreateComment" method="post">
    <div class="form-horizontal">
        <br />
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="CommentText" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="CommentText" class="form-control" rows="4" cols="50"></textarea>
                <span asp-validation-for="CommentText" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Post" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to photo", "ViewPhoto", new { id = ViewBag.photoId })
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GallerySharp/src/GallerySharp/Views/Album/CreateProfile.cshtml
@model GallerySharp.Models.GalleryViewModels.CreateProfileView

@{
    ViewData["Title"] = "Create Profile";
}

<h2>Create your profile</h2>

<form asp-action="CreateProfile">
    <div class="form-horizontal">
        <br />
        <hr />
        <div class="col-md-offset-2 col-md-10">
            @ViewBag.errorMessage
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="UserName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GallerySharp/src/GallerySharp/Views/Album/Index.cshtml
@model IEnumerable<GallerySharp.Models.GalleryModels.Album>

@{
    ViewData["Title"] = "Albums";
}

<h2>Your albums</h2>
<hr style="border:1px solid black" />
<p>
    <a asp-action="CreateAlbum"> &nbsp Create New Album</a>
</p>

@if (Model.Any(a => a.UserID == ViewBag.usId))
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.AlbumName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreationDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Where(a => a.UserID == ViewBag.usId).OrderByDescending(s => s.CreationDate))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AlbumName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreationDate)
                    </td>
                    <td>
                        @Html.ActionLink("Change Name", "ChangeAlbumName", new { id = item.AlbumID }) |
                        @Html.ActionLink("View", "ViewAlbum", new { id = item.AlbumID }) |
                        <a asp-action="DeleteAlbum" asp-route-id="@item.AlbumID" class="confirmation">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4> &nbsp You do not have any albums yet, create one!</h4>
}


<hr />
<h2>Other albums</h2>
<hr style="border:1px solid black" />
@if (Model.Any(a => a.UserID != ViewBag.usId))
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.AlbumName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreationDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Where(a => a.UserID != ViewBag.usId).OrderByDescending(s => s.CreationDate))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AlbumName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreationDate)
                    </td>
                    <td>
                        @Html.ActionLink("View", "ViewAlbum", new { id = item.AlbumID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4> &nbsp There are no other albums of other users yet!</h4>
}

<hr />
<h2>Subscriptions</h2>
<hr style="border:1px solid black"/>
@if (ViewBag.users.Count != 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    UserName
                </th>
                <th>
                    Subscription
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.users)
            {
                <tr>
                    <td>
                        @item.UserName
                    </td>
                    <td>
                        @{
                            if (ViewBag.subs.Contains(item.UserID))
                            {
                                @Html.ActionLink("Unsubscribe", "UnsubscribeToUser", new { id = item.UserID })
                            }
                            else
                            {
                                @Html.ActionLink("  Subscribe", "SubscribeToUser", new { id = item.UserID })
                            }
                        }
                    </td>
                </tr>
                            }
        </tbody>
    </table>
                            }
                            else
                            {
                                <h4>&nbsp There are no other users yet.</h4>
                            }

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GallerySharp/src/GallerySharp/Views/Album/ViewAlbum.cshtml
@model GallerySharp.Models.GalleryModels.Album

@{
    ViewData["Title"] = "Album Viewer";
}

<h2>@Model.AlbumName</h2>

<div>
    <br />
    @if (Model.UserID == ViewBag.userId)
    {
        @Html.ActionLink("Add New Photo", "AddPhoto", new { id = Model.AlbumID })
    }
    <hr />


    @if (Model.Photos.Count != 0)
    {
        <dl class="dl-horizontal">
            @foreach (var photo in Model.Photos.OrderByDescending(d => d.LikeCount).ThenByDescending(d => d.CreationDate))
            {
                <dt>
                    Name: @photo.PhotoName
                    <br />
                    <br />
                    Favoured: @photo.LikeCount
                    @if (photo.UserID == ViewBag.userId)
                    {
                        <br />
                        <br />
                        @Html.ActionLink("Change Name", "ChangePhotoName", new { id = photo.PhotoID })
                        <br />
                        <br />
                        <a asp-action="DeletePhoto" asp-route-id="@photo.PhotoID" class="confirmation">Delete</a>
                    }
                </dt>
                <dd style="margin-bottom:10px">
                    @{
                        String img64 = Convert.ToBase64String(photo.Content);
                        String img64Url = string.Format("data:image/" + photo.ContentType + ";base64,{0}", img64); //imagetype can be e.g. gif, jpeg, png etc.
                    }
                    <a asp-action="ViewPhoto" asp-route-id=@photo.PhotoID>
                        <img src="@img64Url" style="max-width: 25%; height: auto;" />
                    </a>
                    <br />
                </dd>
                        }
        </dl>

                        }
                        else
                        {
                            <h4>Album does not have any photos, add some new ones!</h4>
                        }

</div>
<div>
    <a asp-action="Index">Back to Albums</a>
</div>

GallerySharp/src/GallerySharp/Views/Album/ViewPhoto.cshtml
@model GallerySharp.Models.GalleryModels.Photo

@{
    ViewData["Title"] = "View Photo";
}

<div class="center-block">
    <h2>@Model.PhotoName</h2>
    <hr />
    @{
        String img64 = Convert.ToBase64String(@Model.Content);
        String img64Url = string.Format("data:image/" + @Model.ContentType + ";base64,{0}", img64);
    }
    <div style="position:relative;width:100%;">
        <img src="@img64Url" style="max-width:600px;height:auto;float:left;margin-right:15px;margin-bottom:10px" />
        <table class="table" style="width:auto;border-left:1px solid black;">
            <thead>
                <tr>
                    <th>
                        User Name
                    </th>
                    <th>
                        Comment
                    </th>
                    <th>
                        Creation Date
                    </th>
                    <th></th>
                </tr>
            </thead>
            @if (Model.Comments.Any())
            {
                @foreach (var comment in Model.Comments.OrderByDescending(p => p.CreationDate))
                {
                    <tr>
                        <td>@comment.UserName</td>
                        <td>@comment.CommentText</td>
                        <td>@comment.CreationDate</td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td>No Comments</td>
                </tr>
            }
        </table>
    </div>
    <div style="clear:both;"></div>
    <br />
    <h3>Favoured: @Model.LikeCount</h3>
    <br />
    @Html.ActionLink("Like", "LikePhoto", new { id = Model.PhotoID }) |
    @Html.ActionLink("Dislike", "DislikePhoto", new { id = Model.PhotoID }) |
    @Html.ActionLink("Comment", "CreateComment") |
    @Html.ActionLink("Add To Favorites", "AddPhotoToFavorites", new { id = Model.PhotoID })
    <hr />
</div>

<div>
    <a asp-action="ViewAlbum">Back to Album</a>
</div>